//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTuLuWebProject_prog.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.AuthorByBook = new HashSet<AuthorByBook>();
            this.BookByEditor = new HashSet<BookByEditor>();
            this.BookByUser = new HashSet<BookByUser>();
            this.Review = new HashSet<Review>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> BookNumber { get; set; }
        public string BookCollection { get; set; }
        public string BookSerie { get; set; }
        public int BookLanguage { get; set; }
        public int PageNumber { get; set; }
        public Nullable<int> PublishedYear { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int Score { get; set; }
        public int TimesConsulted { get; set; }
        public Nullable<bool> IsTranslated { get; set; }
        public int BookStatus { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<AuthorByBook> AuthorByBook { get; set; }
        public virtual ICollection<BookByEditor> BookByEditor { get; set; }
        public virtual ICollection<BookByUser> BookByUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}
