//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsTuLuWebProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string CommentText { get; set; }
        public int AccountID { get; set; }
        public int ReviewID { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
