//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstuluProject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookByEditor
    {
        public int BookByEditorId { get; set; }
        public int BookID { get; set; }
        public int EditorID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Editor Editor { get; set; }
    }
}
