//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstuluProject.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Book = new HashSet<Book>();
            this.SubCategory = new HashSet<SubCategory>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public int TimesCategoryConsulted { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
        public virtual ICollection<SubCategory> SubCategory { get; set; }
    }
}
